export type RemnoteCommandInventoryEntry = {
  readonly id: string;
  readonly family: string;
  readonly classification: 'business' | 'business_deferred' | 'operational_host_only';
  readonly wave: 'wave1' | 'wave2' | 'wave3' | 'excluded';
  readonly parityTarget: 'same_support' | 'same_stable_failure' | 'reclassify' | 'host_only';
};

// This file is a derived mirror of docs/ssot/agent-remnote/runtime-mode-and-command-parity.md.
// Keep it synchronized with the authoritative doc; contract tests enforce drift.
export const remnoteCommandInventory: readonly RemnoteCommandInventoryEntry[] = [
  { id: 'search', family: 'search_outline', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.outline', family: 'search_outline', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'daily.rem-id', family: 'search_outline', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'page-id', family: 'ref_reads', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'by-reference', family: 'ref_reads', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'references', family: 'ref_reads', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'resolve-ref', family: 'ref_reads', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'query', family: 'ref_reads', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'plugin.current', family: 'ui_context', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'plugin.search', family: 'ui_context', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'plugin.ui-context.snapshot', family: 'ui_context', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'plugin.ui-context.page', family: 'ui_context', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'plugin.ui-context.focused-rem', family: 'ui_context', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'plugin.ui-context.describe', family: 'ui_context', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'plugin.selection.current', family: 'selection_context', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'plugin.selection.snapshot', family: 'selection_context', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'plugin.selection.roots', family: 'selection_context', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'plugin.selection.outline', family: 'selection_context', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'daily.write', family: 'core_writes', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'apply', family: 'core_writes', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'queue.wait', family: 'core_writes', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.create', family: 'rem_graph_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.move', family: 'rem_graph_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'portal.create', family: 'relation_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.replace', family: 'rem_graph_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.children.append', family: 'rem_graph_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.children.prepend', family: 'rem_graph_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.children.clear', family: 'rem_graph_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.children.replace', family: 'rem_graph_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.set-text', family: 'rem_graph_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.delete', family: 'rem_graph_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'tag.add', family: 'relation_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'tag.remove', family: 'relation_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.tag.add', family: 'relation_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'rem.tag.remove', family: 'relation_write', classification: 'business', wave: 'wave1', parityTarget: 'same_support' },
  { id: 'table.show', family: 'table_reads', classification: 'business_deferred', wave: 'wave2', parityTarget: 'same_support' },
  { id: 'table.create', family: 'table_writes', classification: 'business_deferred', wave: 'wave2', parityTarget: 'same_support' },
  { id: 'table.property.add', family: 'table_writes', classification: 'business_deferred', wave: 'wave2', parityTarget: 'same_stable_failure' },
  { id: 'table.property.set-type', family: 'table_writes', classification: 'business_deferred', wave: 'wave2', parityTarget: 'same_stable_failure' },
  { id: 'table.option.add', family: 'table_writes', classification: 'business_deferred', wave: 'wave2', parityTarget: 'same_support' },
  { id: 'table.option.remove', family: 'table_writes', classification: 'business_deferred', wave: 'wave2', parityTarget: 'same_support' },
  { id: 'table.record.add', family: 'table_writes', classification: 'business_deferred', wave: 'wave2', parityTarget: 'same_support' },
  { id: 'table.record.update', family: 'table_writes', classification: 'business_deferred', wave: 'wave2', parityTarget: 'same_support' },
  { id: 'table.record.delete', family: 'table_writes', classification: 'business_deferred', wave: 'wave2', parityTarget: 'same_support' },
  { id: 'powerup.list', family: 'powerup_reads', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.resolve', family: 'powerup_reads', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.schema', family: 'powerup_reads', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.apply', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.remove', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.property.add', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_stable_failure' },
  { id: 'powerup.property.set-type', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_stable_failure' },
  { id: 'powerup.option.add', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.option.remove', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.record.add', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.record.update', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.record.delete', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.todo.add', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.todo.done', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.todo.remove', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'powerup.todo.undone', family: 'powerup_writes', classification: 'business_deferred', wave: 'wave3', parityTarget: 'same_support' },
  { id: 'connections', family: 'analytical_reads', classification: 'business_deferred', wave: 'excluded', parityTarget: 'reclassify' },
  { id: 'daily.summary', family: 'analytical_reads', classification: 'business_deferred', wave: 'excluded', parityTarget: 'reclassify' },
  { id: 'topic.summary', family: 'analytical_reads', classification: 'business_deferred', wave: 'excluded', parityTarget: 'reclassify' },
  { id: 'inspect', family: 'analytical_reads', classification: 'business_deferred', wave: 'excluded', parityTarget: 'reclassify' },
  { id: 'todos.list', family: 'analytical_reads', classification: 'business_deferred', wave: 'excluded', parityTarget: 'reclassify' },
  { id: 'api.*', family: 'operational_lifecycle', classification: 'operational_host_only', wave: 'excluded', parityTarget: 'host_only' },
  { id: 'stack.*', family: 'operational_lifecycle', classification: 'operational_host_only', wave: 'excluded', parityTarget: 'host_only' },
  { id: 'daemon.*', family: 'operational_lifecycle', classification: 'operational_host_only', wave: 'excluded', parityTarget: 'host_only' },
  { id: 'backup.*', family: 'operational_lifecycle', classification: 'operational_host_only', wave: 'excluded', parityTarget: 'host_only' },
  { id: 'config.*', family: 'operational_lifecycle', classification: 'operational_host_only', wave: 'excluded', parityTarget: 'host_only' },
  { id: 'doctor.*', family: 'operational_lifecycle', classification: 'operational_host_only', wave: 'excluded', parityTarget: 'host_only' },
  { id: 'queue.inspect', family: 'operational_lifecycle', classification: 'operational_host_only', wave: 'excluded', parityTarget: 'host_only' },
  { id: 'queue.progress', family: 'operational_lifecycle', classification: 'operational_host_only', wave: 'excluded', parityTarget: 'host_only' },
  { id: 'queue.stats', family: 'operational_lifecycle', classification: 'operational_host_only', wave: 'excluded', parityTarget: 'host_only' },
  { id: 'queue.conflicts', family: 'operational_lifecycle', classification: 'operational_host_only', wave: 'excluded', parityTarget: 'host_only' },
] as const;
