export const wave1RemnoteBusinessCommandContractIds = [
  'search',
  'rem.outline',
  'daily.rem-id',
  'page-id',
  'by-reference',
  'references',
  'resolve-ref',
  'query',
  'plugin.current',
  'plugin.search',
  'plugin.ui-context.snapshot',
  'plugin.ui-context.page',
  'plugin.ui-context.focused-rem',
  'plugin.ui-context.describe',
  'plugin.selection.current',
  'plugin.selection.snapshot',
  'plugin.selection.roots',
  'plugin.selection.outline',
  'daily.write',
  'apply',
  'queue.wait',
  'rem.create',
  'rem.move',
  'portal.create',
  'rem.replace',
  'rem.children.append',
  'rem.children.prepend',
  'rem.children.clear',
  'rem.children.replace',
  'rem.set-text',
  'rem.delete',
  'tag.add',
  'tag.remove',
  'rem.tag.add',
  'rem.tag.remove',
] as const;

export const approvedWave1ModeInfrastructureFiles = [
  'packages/agent-remnote/src/lib/business-semantics/commandContracts.ts',
  'packages/agent-remnote/src/lib/business-semantics/modeParityRuntime.ts',
  'packages/agent-remnote/src/lib/business-semantics/localModeAdapter.ts',
  'packages/agent-remnote/src/lib/business-semantics/remoteModeAdapter.ts',
  'packages/agent-remnote/src/lib/business-semantics/capabilityGuards.ts',
] as const;

export const wave1BusinessCommandFiles = [
  'packages/agent-remnote/src/commands/read/search.ts',
  'packages/agent-remnote/src/commands/read/outline.ts',
  'packages/agent-remnote/src/commands/read/page-id.ts',
  'packages/agent-remnote/src/commands/read/by-reference.ts',
  'packages/agent-remnote/src/commands/read/references.ts',
  'packages/agent-remnote/src/commands/read/resolve-ref.ts',
  'packages/agent-remnote/src/commands/read/query.ts',
  'packages/agent-remnote/src/commands/daily/rem-id.ts',
  'packages/agent-remnote/src/commands/plugin/current.ts',
  'packages/agent-remnote/src/commands/plugin/search.ts',
  'packages/agent-remnote/src/commands/read/uiContext/snapshot.ts',
  'packages/agent-remnote/src/commands/read/uiContext/page.ts',
  'packages/agent-remnote/src/commands/read/uiContext/focused-rem.ts',
  'packages/agent-remnote/src/commands/read/uiContext/describe.ts',
  'packages/agent-remnote/src/commands/read/selection/current.ts',
  'packages/agent-remnote/src/commands/read/selection/snapshot.ts',
  'packages/agent-remnote/src/commands/read/selection/roots.ts',
  'packages/agent-remnote/src/commands/read/selection/outline.ts',
  'packages/agent-remnote/src/commands/daily/write.ts',
  'packages/agent-remnote/src/commands/apply.ts',
  'packages/agent-remnote/src/commands/queue/wait.ts',
  'packages/agent-remnote/src/commands/write/rem/create.ts',
  'packages/agent-remnote/src/commands/write/rem/move.ts',
  'packages/agent-remnote/src/commands/write/portal/create.ts',
  'packages/agent-remnote/src/commands/write/rem/replace.ts',
  'packages/agent-remnote/src/commands/write/rem/children/append.ts',
  'packages/agent-remnote/src/commands/write/rem/children/prepend.ts',
  'packages/agent-remnote/src/commands/write/rem/children/clear.ts',
  'packages/agent-remnote/src/commands/write/rem/children/replace.ts',
  'packages/agent-remnote/src/commands/write/rem/text.ts',
  'packages/agent-remnote/src/commands/write/rem/delete.ts',
  'packages/agent-remnote/src/commands/write/tag/index.ts',
] as const;
